---
- name: Install epel-release
  yum:
    name:
    - epel-release

# Install packets
- name: install base tools
  package:
    name:
#    - epel-release
    - openvpn
    state: present

# Copy server.conf file
- name: copy server conf file 
  copy:
    src: server.conf
    dest: /etc/openvpn/server.conf

# Copy openvpn service file
- name: copy openvpn service file 
  copy:
    src: openvpn.service
    dest: /etc/systemd/system/openvpn@.service

# Create crt directory
- name: Create pki directory
  file:
    path: /etc/openvpn/pki
    state: directory
    mode: '0755'

- name: Create private directory
  file:
    path: /etc/openvpn/pki/private
    state: directory
    mode: '0755'
    
- name: Create issued directory
  file:
    path: /etc/openvpn/pki/issued
    state: directory
    mode: '0755'

# Copy key file
- name: copy key file 
  copy:
    src: server.key
    dest: /etc/openvpn/pki/private/server.key

# Copy server.crt file
- name: copy server.crt file 
  copy:
    src: server.crt
    dest: /etc/openvpn/pki/issued/server.crt

# Copy ca.crt file
- name: copy ca.crt file 
  copy:
    src: ca.crt
    dest: /etc/openvpn/pki/ca.crt

# Copy dh.pem file
- name: copy pem file 
  copy:
    src: dh.pem
    dest: /etc/openvpn/pki/dh.pem

# Add route
- name: Add route
  shell: echo 'ip route 10.10.10.0 255.255.255.0' > /etc/openvpn/client/client

# Start and enable openvpn service
- name: start openvpn service
  systemd:
    name: openvpn@server
    state: started
    enabled: true

...
